version: '3.7'
services:
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_network
 
networks:
  keycloak_network:
    driver: bridge